### PR TITLE
Update clj-http

### PR DESCRIPTION
**Pull request by AeroNotix**
Ref: https://github.com/ztellman/aleph/issues/134

### CODE REVIEW

**Comment by AeroNotix** [comment]
This works for me locally, any ideas?

**Comment by aphyr** [comment]
I don't think we should explicitly depend on Potemkin; it's a clj-http dependency; makes sense to let them handle it.

**Comment by aphyr** [comment]
Build errors look like a clj-http/potemkin version mismatch. Bet you if you drop the potemkin dep it'll work out OK.

**Comment by AeroNotix** [comment]
@aphyr indeed. The context is in that ticket I linked. I guess I'll wait till clj-http makes another release before using aleph with Riemann.

**Comment by aphyr** [comment]
Done and done, thanks for the bump Aaron! :)

**Comment by AeroNotix** [comment]
:+1:

**Comment by aphyr** [comment]
So whatever bug this is seems related to clj-http 1.0.1; I don't see any conflicting deps for potemkin, so I'm not sure why 1.0.1 should have problems. Dropping to clj-http 1.0.0 works correctly. cc @ztellman

**Pull request merged**
