### PR TITLE
JSON write schema 'name' key was renamed to 'measurement'

### PR DESCRIPTION
**Pull request by kurman**
See https://github.com/influxdb/influxdb/issues/2564

### CODE REVIEW

**Comment by bfritz** [comment]
@kurman Not certain, but this might be a dup of #569, #574 or #575:
https://github.com/aphyr/riemann/search?utf8=%E2%9C%93&q=influx+AND+measurement&type=Issues

**Comment by kurman** [comment]
Yes, this one is definitely a duplicate. I will close my PR. But we need a
fix on the master branch sooner than later.

Kurman

**Comment by aphyr** [comment]
Yeah, I know, sorry y'all. I've been incredibly backed up lately.

**Comment by kurman** [comment]
Thank you Kyle. And while at it, what are your planned schedule on cutting
v.0.2.10?

Kurman

**Comment by aphyr** [comment]
Sometime after I get back from camping this weekend?

**Comment by kurman** [comment]
You rock :)

Thanks again.
Kurman

**Pull request closed without merging**
